# /pel.config.yml
# Version: 1.0
# This file is the single source of truth for the PEL's architectural rules.

# Defines the search order for persona and template resolution.
resolution_paths:
  - "project"   # Look in the project's /personas directory first.
  - "template"  # Then look in the associated template's /personas directory.

# Defines valid persona types and their validation rules.
# The validator script will now read a 'type' key from the persona's
# frontmatter and use these rules, instead of relying on file paths.
persona_types:
  specialized:
    required_keys:
      - "alias"
      - "version"
      - "title"
      - "status"
      - "inherits_from"
      - "expected_artifacts"
  base:
    required_keys:
      - "alias"
      - "version"
      - "title"
      - "status"
  mixin:
    required_keys:
      - "alias"
      - "version"
      - "title"
      - "status"
  utility: 
    required_keys:
      - "alias"
      - "version"
      - "title"
      - "status"
      - "expected_artifacts"

# Defines the standard for instance files and their lifecycle.
instance_governance:
  # Defines the directory where completed instances will be moved.
  archive_dir: "archive"
  # Defines the standardized filename format for archived instances.
  # Example: 2023-10-27_implement-auth-v2_complete.instance.md
  filename_format: "{YYYY-MM-DD}_{instance_id}_{status}.instance.md"
  valid_stati:
    - "pending"
    - "complete"
    - "failed"
    
# Defines which persona statuses the validation script should process.
# Any persona with a status not in this list will be skipped.
validation_rules:
  active_stati:
    - "active"