# Development-specific overrides
services:
  redis:
    ports: ["6380:6379", "8001:8001"]
    volumes: [redis-data-dev:/data]
    command:
      - redis-server
      - "--bind 0.0.0.0"
      - "--protected-mode no"

  postgres:
    ports: ["5432:5432"]
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  redis-data-dev:
  pgdata-dev:
